// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BlueNilePds.Pds.PendingAccounts;

#nullable disable

namespace BlueNilePds.Pds.PendingAccounts.Migrations
{
    [DbContext(typeof(PendingAccountsDb))]
    [Migration("20260826094830_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BlueNilePds.Pds.PendingAccounts.Models.PendingEmailToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewEmail")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingRegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PendingRegistrationId", "Purpose");

                    b.ToTable("PendingEmailTokens");
                });

            modelBuilder.Entity("BlueNilePds.Pds.PendingAccounts.Models.PendingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarBlobRef")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingRegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PendingRegistrationId")
                        .IsUnique();

                    b.ToTable("PendingProfiles");
                });

            modelBuilder.Entity("BlueNilePds.Pds.PendingAccounts.Models.PendingRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordScrypt")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Handle")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("PendingRegistrations");
                });

            modelBuilder.Entity("BlueNilePds.Pds.PendingAccounts.Models.PendingProfile", b =>
                {
                    b.HasOne("BlueNilePds.Pds.PendingAccounts.Models.PendingRegistration", "PendingRegistration")
                        .WithMany()
                        .HasForeignKey("PendingRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PendingRegistration");
                });
#pragma warning restore 612, 618
        }
    }
}
