<Project Sdk="Microsoft.NET.Sdk">

        <ItemGroup>
        <PackageReference Include="jose-jwt" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Scrypt.NET" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\projects\CID\CID.csproj" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <ProjectReference Include="..\Config\Config.csproj" />
        <ProjectReference Include="..\Xrpc\Xrpc.csproj" />
    </ItemGroup>

</Project>
