// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sequencer.Db;

#nullable disable

namespace Sequencer.Migrations
{
    [DbContext(typeof(SequencerDb))]
    [Migration("20241207005517_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Sequencer.Db.RepoSeq", b =>
                {
                    b.Property<int>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Did")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Event")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Invalidated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SequencedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Seq");

                    b.ToTable("RepoSeqs");
                });
#pragma warning restore 612, 618
        }
    }
}
