<Project Sdk="Microsoft.NET.Sdk">

        <ItemGroup>
        <ProjectReference Include="..\..\pds_projects\Config\Config.csproj"/>
        <ProjectReference Include="..\..\pds_projects\Xrpc\Xrpc.csproj"/>
        <ProjectReference Include="..\Identity\Identity.csproj"/>
    </ItemGroup>

</Project>
